{
  ...
}: {
  imports = [
    ./main.nix 
    ./keybinds.nix
    ./zen-mode.nix
    ./none-ls.nix
    ./telescope.nix
    ./completions.nix
    ./lspconfig.nix
    ./lazygit.nix
    ./which-key.nix
    ./cheatsheet.nix
    ./colorizer.nix
    ./tmux-navigator.nix
    ./trouble.nix
    ./nvim-surround.nix
    ./custom-lsp.nix
    ./markdown.nix
    ./theme.nix
    ./statusline.nix
    ./oil.nix
    ./harpoon.nix
    ./dashboard.nix
    ./icons.nix
    ./noice.nix
    ./snacks.nix
    ./treesitter.nix
    ./image.nix
    ./fastaction.nix
    ./git.nix
    ./flash.nix
    ./multi-cursor.nix
    ./csv.nix
  ];
}
